### ISSUE TITLE
Fix bug in f2pool causing script termination

### ISSUE THREAD

**Issue by vicariousdrama** [vicariousdrama/nodeyez#47]
An error can occur in the script when calling getaccountinfo() that can cause the script to fail.

A typical Traceback appears as folows
```python
 Traceback (most recent call last):
   File "/home/bitcoin/nodeyez/scripts/f2pool.py", line 250, in <module>
     accountinfo = getaccountinfo()
   File "/home/bitcoin/nodeyez/scripts/f2pool.py", line 19, in getaccountinfo
     j = json.loads(cmdoutput)
   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
     return _default_decoder.decode(s)
   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
     raise JSONDecodeError("Expecting value", s, err.value) from None
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Recommend a check for the length of cmdoutput before loading as json

**Comment by vicariousdrama** [comment]
Closed by #49
